### ISSUE TITLE
cannot get PI 4 to boot after hardware connected

### ISSUE THREAD

**Issue by tnesseth1** [flatmax/AudioInjector.Octo.template#1]
will not boot with hardware connected 

let me know if i got a bum one and need a another? or if i'm doing something wrong it's been a week and three days

**Comment by flatmax** [comment]
Please ask Octo related issues on the octo hardware page.

**Comment by tnesseth1** [comment]
understood


-- 
Ted Nesseth
Business Analyst | Process Engineer | Salesforce Implementation Consultant 
***@***.***
737.210.2445
